../../target/agt/agt.o: agt.c ../platform/procdefs.h agt.h ../ncx/help.h \
 ../ncx/ncxconst.h ../ncx/obj.h ../ncx/log.h ../ncx/status.h ../ncx/grp.h \
 ../ncx/ncxtypes.h ../ncx/dlq.h ../ncx/xmlns.h ../ncx/tk.h ../ncx/rpc.h \
 ../ncx/op.h ../ncx/val.h ../ncx/plock_cb.h ../ncx/tstamp.h ../ncx/typ.h \
 ../ncx/xml_util.h ../ncx/ses.h ../ncx/xml_msg.h agt_acm.h ../ncx/xpath.h \
 ../ncx/var.h ../ncx/runstack.h ../ncx/yang.h ../ncx/ext.h \
 agt_acm_extern.h agt_cap.h ../ncx/cap.h agt_cb.h ../ncx/op.h \
 ../ncx/rpc.h ../ncx/ses.h ../ncx/status.h ../ncx/val.h agt_cfg.h \
 ../ncx/cfg.h ../ncx/ncx.h ../ncx/plock.h ../ncx/val_util.h \
 agt_commit_complete.h agt_cli.h agt_connect.h agt_hello.h \
 agt_ietf_notif.h ../ncx/dlq.h ../ncx/ncxtypes.h agt_if.h agt_ncx.h \
 agt_not.h agt_plock.h agt_proc.h agt_rpc.h ../ncx/rpc_err.h agt_ses.h \
 ../ncx/getcb.h agt_signal.h agt_state.h agt_sys.h agt_val.h \
 agt_time_filter.h agt_timer.h agt_util.h agt_yuma_arp.h ../ncx/log.h \
 ../ncx/log_vendor.h ../ncx/log_util.h ../ncx/log_vendor_extern.h \
 ../ncx/ncx.h ../ncx/ncx_str.h ../ncx/ncxconst.h ../ncx/ncxmod.h
