../../target/agt/agt_cli.o: agt_cli.c ../platform/procdefs.h agt_cli.h \
 agt.h ../ncx/help.h ../ncx/ncxconst.h ../ncx/obj.h ../ncx/log.h \
 ../ncx/status.h ../ncx/grp.h ../ncx/ncxtypes.h ../ncx/dlq.h \
 ../ncx/xmlns.h ../ncx/tk.h ../ncx/rpc.h ../ncx/op.h ../ncx/val.h \
 ../ncx/plock_cb.h ../ncx/tstamp.h ../ncx/typ.h ../ncx/xml_util.h \
 ../ncx/ses.h ../ncx/xml_msg.h ../ncx/cli.h ../ncx/runstack.h \
 ../ncx/conf.h ../ncx/ncx.h ../ncx/yang.h ../ncx/ext.h ../ncx/ncx_list.h \
 ../ncx/ncxconst.h ../ncx/obj.h ../ncx/status.h ../ncx/val.h \
 ../ncx/val_util.h ../ncx/plock.h ../ncx/xpath.h ../ncx/var.h
