../../target/agt/agt_acm_ietf.o: agt_acm_ietf.c ../platform/procdefs.h \
 agt.h ../ncx/help.h ../ncx/ncxconst.h ../ncx/obj.h ../ncx/log.h \
 ../ncx/status.h ../ncx/grp.h ../ncx/ncxtypes.h ../ncx/dlq.h \
 ../ncx/xmlns.h ../ncx/tk.h ../ncx/rpc.h ../ncx/op.h ../ncx/val.h \
 ../ncx/plock_cb.h ../ncx/tstamp.h ../ncx/typ.h ../ncx/xml_util.h \
 ../ncx/ses.h ../ncx/xml_msg.h agt_acm.h ../ncx/xpath.h ../ncx/var.h \
 ../ncx/runstack.h ../ncx/yang.h ../ncx/ext.h agt_acm_ietf.h agt_cb.h \
 ../ncx/op.h ../ncx/rpc.h ../ncx/ses.h ../ncx/status.h ../ncx/val.h \
 agt_not.h agt_ses.h ../ncx/getcb.h agt_util.h ../ncx/cfg.h ../ncx/ncx.h \
 ../ncx/plock.h ../ncx/val_util.h agt_val.h agt_cfg.h ../ncx/def_reg.h \
 ../ncx/dlq.h ../ncx/ncx.h ../ncx/ncx_num.h ../ncx/ncx_list.h \
 ../ncx/ncxconst.h ../ncx/ncxmod.h ../ncx/cap.h ../ncx/obj.h \
 ../ncx/val_util.h ../ncx/xmlns.h ../ncx/xpath1.h
