../../target/agt/agt_ncxserver.o: agt_ncxserver.c ../platform/procdefs.h \
 agt.h ../ncx/help.h ../ncx/ncxconst.h ../ncx/obj.h ../ncx/log.h \
 ../ncx/status.h ../ncx/grp.h ../ncx/ncxtypes.h ../ncx/dlq.h \
 ../ncx/xmlns.h ../ncx/tk.h ../ncx/rpc.h ../ncx/op.h ../ncx/val.h \
 ../ncx/plock_cb.h ../ncx/tstamp.h ../ncx/typ.h ../ncx/xml_util.h \
 ../ncx/ses.h ../ncx/xml_msg.h agt_ncxserver.h agt_not.h agt_rpc.h \
 ../ncx/cfg.h ../ncx/ncx.h ../ncx/yang.h ../ncx/ext.h ../ncx/plock.h \
 ../ncx/xpath.h ../ncx/var.h ../ncx/runstack.h ../ncx/val_util.h \
 ../ncx/rpc_err.h agt_ses.h ../ncx/getcb.h agt_timer.h ../ncx/def_reg.h \
 ../ncx/log.h ../ncx/ncx.h ../ncx/ncxconst.h ../ncx/ses.h \
 ../ncx/ses_msg.h ../ncx/status.h ../ncx/xmlns.h
