../../target/agt/agt_ses.o: agt_ses.c ../platform/procdefs.h agt.h \
 ../ncx/help.h ../ncx/ncxconst.h ../ncx/obj.h ../ncx/log.h \
 ../ncx/status.h ../ncx/grp.h ../ncx/ncxtypes.h ../ncx/dlq.h \
 ../ncx/xmlns.h ../ncx/tk.h ../ncx/rpc.h ../ncx/op.h ../ncx/val.h \
 ../ncx/plock_cb.h ../ncx/tstamp.h ../ncx/typ.h ../ncx/xml_util.h \
 ../ncx/ses.h ../ncx/xml_msg.h agt_acm.h ../ncx/xpath.h ../ncx/var.h \
 ../ncx/runstack.h ../ncx/yang.h ../ncx/ext.h agt_cb.h ../ncx/op.h \
 ../ncx/rpc.h ../ncx/ses.h ../ncx/status.h ../ncx/val.h agt_connect.h \
 ../ncx/cfg.h ../ncx/ncx.h ../ncx/plock.h ../ncx/val_util.h agt_ncx.h \
 agt_ncxserver.h agt_rpc.h ../ncx/rpc_err.h agt_ses.h ../ncx/getcb.h \
 agt_state.h agt_not.h agt_sys.h agt_top.h agt_util.h ../ncx/def_reg.h \
 ../ncx/log.h ../ncx/ncxmod.h ../ncx/cap.h ../ncx/ses_msg.h \
 ../ncx/tstamp.h ../ncx/xmlns.h ../ncx/xml_util.h
