../../target/agt/agt_acm_extern.o: agt_acm_extern.c \
 ../platform/procdefs.h agt.h ../ncx/help.h ../ncx/ncxconst.h \
 ../ncx/obj.h ../ncx/log.h ../ncx/status.h ../ncx/grp.h ../ncx/ncxtypes.h \
 ../ncx/dlq.h ../ncx/xmlns.h ../ncx/tk.h ../ncx/rpc.h ../ncx/op.h \
 ../ncx/val.h ../ncx/plock_cb.h ../ncx/tstamp.h ../ncx/typ.h \
 ../ncx/xml_util.h ../ncx/ses.h ../ncx/xml_msg.h agt_acm.h ../ncx/xpath.h \
 ../ncx/var.h ../ncx/runstack.h ../ncx/yang.h ../ncx/ext.h \
 agt_acm_extern.h ../ncx/ncxconst.h ../ncx/obj.h ../ncx/op.h \
 ../ncx/status.h ../ncx/val.h
