../../target/agt/agt_cfg.o: agt_cfg.c ../platform/procdefs.h agt.h \
 ../ncx/help.h ../ncx/ncxconst.h ../ncx/obj.h ../ncx/log.h \
 ../ncx/status.h ../ncx/grp.h ../ncx/ncxtypes.h ../ncx/dlq.h \
 ../ncx/xmlns.h ../ncx/tk.h ../ncx/rpc.h ../ncx/op.h ../ncx/val.h \
 ../ncx/plock_cb.h ../ncx/tstamp.h ../ncx/typ.h ../ncx/xml_util.h \
 ../ncx/ses.h ../ncx/xml_msg.h agt_cfg.h ../ncx/cfg.h ../ncx/ncx.h \
 ../ncx/yang.h ../ncx/ext.h ../ncx/plock.h ../ncx/xpath.h ../ncx/var.h \
 ../ncx/runstack.h ../ncx/val_util.h agt_util.h ../ncx/getcb.h \
 ../ncx/dlq.h ../ncx/log.h ../ncx/ncx.h ../ncx/ncx_num.h \
 ../ncx/ncxconst.h ../ncx/obj.h ../ncx/op.h ../ncx/rpc.h ../ncx/rpc_err.h \
 ../ncx/status.h ../ncx/val.h ../ncx/val_util.h
