../../target/agt/agt_cb.o: agt_cb.c agt_cb.h agt.h ../ncx/help.h \
 ../ncx/ncxconst.h ../ncx/obj.h ../ncx/log.h ../platform/procdefs.h \
 ../ncx/status.h ../ncx/grp.h ../ncx/ncxtypes.h ../ncx/dlq.h \
 ../ncx/xmlns.h ../ncx/tk.h ../ncx/rpc.h ../ncx/op.h ../ncx/val.h \
 ../ncx/plock_cb.h ../ncx/tstamp.h ../ncx/typ.h ../ncx/xml_util.h \
 ../ncx/ses.h ../ncx/xml_msg.h ../ncx/op.h ../ncx/rpc.h ../ncx/ses.h \
 ../ncx/status.h ../ncx/val.h agt_util.h ../ncx/cfg.h ../ncx/ncx.h \
 ../ncx/yang.h ../ncx/ext.h ../ncx/plock.h ../ncx/xpath.h ../ncx/var.h \
 ../ncx/runstack.h ../ncx/val_util.h ../ncx/getcb.h ../ncx/obj.h \
 ../ncx/xpath.h ../ncx/yang.h
