../../target/agt/agt_rpcerr.o: agt_rpcerr.c ../platform/procdefs.h \
 agt_rpc.h ../ncx/cfg.h ../ncx/dlq.h ../ncx/ncx.h ../ncx/grp.h \
 ../ncx/ncxconst.h ../ncx/ncxtypes.h ../ncx/xmlns.h ../ncx/status.h \
 ../ncx/tk.h ../ncx/log.h ../ncx/obj.h ../ncx/rpc.h ../ncx/op.h \
 ../ncx/val.h ../ncx/plock_cb.h ../ncx/tstamp.h ../ncx/typ.h \
 ../ncx/xml_util.h ../ncx/ses.h ../ncx/xml_msg.h ../ncx/yang.h \
 ../ncx/ext.h ../ncx/plock.h ../ncx/xpath.h ../ncx/var.h \
 ../ncx/runstack.h ../ncx/val_util.h ../ncx/rpc_err.h agt_rpcerr.h \
 ../ncx/def_reg.h ../ncx/ncx.h ../ncx/ncxconst.h ../ncx/rpc.h \
 ../ncx/status.h ../ncx/val.h ../ncx/val_util.h ../ncx/xmlns.h \
 ../ncx/xml_util.h ../ncx/xpath.h
