../../target/agt/agt_val.o: agt_val.c ../platform/procdefs.h agt.h \
 ../ncx/help.h ../ncx/ncxconst.h ../ncx/obj.h ../ncx/log.h \
 ../ncx/status.h ../ncx/grp.h ../ncx/ncxtypes.h ../ncx/dlq.h \
 ../ncx/xmlns.h ../ncx/tk.h ../ncx/rpc.h ../ncx/op.h ../ncx/val.h \
 ../ncx/plock_cb.h ../ncx/tstamp.h ../ncx/typ.h ../ncx/xml_util.h \
 ../ncx/ses.h ../ncx/xml_msg.h agt_acm.h ../ncx/xpath.h ../ncx/var.h \
 ../ncx/runstack.h ../ncx/yang.h ../ncx/ext.h agt_cap.h ../ncx/cap.h \
 agt_cb.h ../ncx/op.h ../ncx/rpc.h ../ncx/ses.h ../ncx/status.h \
 ../ncx/val.h agt_cfg.h ../ncx/cfg.h ../ncx/ncx.h ../ncx/plock.h \
 ../ncx/val_util.h agt_commit_complete.h agt_ncx.h agt_util.h \
 ../ncx/getcb.h agt_val.h agt_val_parse.h ../ncx/dlq.h ../ncx/log.h \
 ../ncx/ncx.h ../ncx/ncxconst.h ../ncx/obj.h ../ncx/plock.h \
 ../ncx/rpc_err.h ../ncx/typ.h ../ncx/tstamp.h ../ncx/val_util.h \
 ../ncx/xmlns.h ../ncx/xpath_yang.h ../ncx/xpath1.h ../ncx/yangconst.h
