../../target/agt/agt_rpc.o: agt_rpc.c ../platform/procdefs.h agt_acm.h \
 agt.h ../ncx/help.h ../ncx/ncxconst.h ../ncx/obj.h ../ncx/log.h \
 ../ncx/status.h ../ncx/grp.h ../ncx/ncxtypes.h ../ncx/dlq.h \
 ../ncx/xmlns.h ../ncx/tk.h ../ncx/rpc.h ../ncx/op.h ../ncx/val.h \
 ../ncx/plock_cb.h ../ncx/tstamp.h ../ncx/typ.h ../ncx/xml_util.h \
 ../ncx/ses.h ../ncx/xml_msg.h ../ncx/xpath.h ../ncx/var.h \
 ../ncx/runstack.h ../ncx/yang.h ../ncx/ext.h agt_cfg.h ../ncx/cfg.h \
 ../ncx/ncx.h ../ncx/plock.h ../ncx/val_util.h agt_cli.h agt_rpc.h \
 ../ncx/rpc_err.h agt_rpcerr.h agt_ses.h ../ncx/getcb.h agt_sys.h \
 agt_util.h agt_val.h agt_val_parse.h agt_xml.h ../ncx/dlq.h \
 ../ncx/json_wr.h ../ncx/log.h ../ncx/ncx.h ../ncx/ncx_num.h \
 ../ncx/ncxconst.h ../ncx/obj.h ../ncx/rpc.h ../ncx/ses.h ../ncx/status.h \
 ../ncx/top.h ../ncx/val.h ../ncx/val_util.h ../ncx/xmlns.h \
 ../ncx/xml_msg.h ../ncx/xml_util.h ../ncx/xml_wr.h ../ncx/yangconst.h
