../../target/agt/agt_hello.o: agt_hello.c ../platform/procdefs.h agt.h \
 ../ncx/help.h ../ncx/ncxconst.h ../ncx/obj.h ../ncx/log.h \
 ../ncx/status.h ../ncx/grp.h ../ncx/ncxtypes.h ../ncx/dlq.h \
 ../ncx/xmlns.h ../ncx/tk.h ../ncx/rpc.h ../ncx/op.h ../ncx/val.h \
 ../ncx/plock_cb.h ../ncx/tstamp.h ../ncx/typ.h ../ncx/xml_util.h \
 ../ncx/ses.h ../ncx/xml_msg.h agt_cap.h ../ncx/cap.h agt_hello.h \
 agt_ses.h ../ncx/getcb.h agt_util.h ../ncx/cfg.h ../ncx/ncx.h \
 ../ncx/yang.h ../ncx/ext.h ../ncx/plock.h ../ncx/xpath.h ../ncx/var.h \
 ../ncx/runstack.h ../ncx/val_util.h agt_val_parse.h ../ncx/log.h \
 ../ncx/ncx.h ../ncx/obj.h ../ncx/op.h ../ncx/ses.h ../ncx/status.h \
 ../ncx/top.h ../ncx/val.h ../ncx/xml_wr.h
