../../target/agt/agt_top.o: agt_top.c ../platform/procdefs.h agt.h \
 ../ncx/help.h ../ncx/ncxconst.h ../ncx/obj.h ../ncx/log.h \
 ../ncx/status.h ../ncx/grp.h ../ncx/ncxtypes.h ../ncx/dlq.h \
 ../ncx/xmlns.h ../ncx/tk.h ../ncx/rpc.h ../ncx/op.h ../ncx/val.h \
 ../ncx/plock_cb.h ../ncx/tstamp.h ../ncx/typ.h ../ncx/xml_util.h \
 ../ncx/ses.h ../ncx/xml_msg.h agt_ses.h ../ncx/getcb.h agt_top.h \
 agt_xml.h ../ncx/dlq.h ../ncx/log.h ../ncx/ncxconst.h ../ncx/ncx.h \
 ../ncx/yang.h ../ncx/ext.h ../ncx/status.h ../ncx/top.h ../ncx/xmlns.h \
 ../ncx/xml_util.h
