usr/bin/yangdump-pro
usr/bin/yangdiff-pro
usr/bin/make_sil_dir_pro
usr/sbin/netconfd-pro
usr/sbin/netconf-subsystem-pro
usr/man/man1/yangdiff-pro.1.gz
usr/man/man1/yangdump-pro.1.gz
usr/man/man1/netconfd-pro.1.gz
usr/man/man1/netconf-subsystem-pro.1.gz
usr/man/man1/make_sil_dir_pro.sh.1.gz
usr/share/doc/yumapro/
usr/share/yumapro/
usr/include/yumapro/
usr/lib/yumapro/
etc/yumapro/yangdiff-pro-sample.conf
etc/yumapro/yangdump-pro-sample.conf
etc/yumapro/netconfd-pro-sample.conf




