
/* 
 * Copyright (c) 2008-2012, Andy Bierman, All Rights Reserved.
 * Copyright (c) 2012, YumaWorks, Inc., All Rights Reserved.
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *

*** Generated by yangdump-pro v12.09-60-g44c6af9

    Combined SIL module
    module sil-error
    revision 2012-11-24
    namespace http://www.netconfcentral.org/ns/sil-error

 */

#include <xmlstring.h>

#include "procdefs.h"
#include "agt.h"
#include "agt_cb.h"
#include "agt_timer.h"
#include "agt_util.h"
#include "dlq.h"
#include "ncx.h"
#include "ncx_feature.h"
#include "ncxmod.h"
#include "ncxtypes.h"
#include "status.h"
#include "sil-error.h"

/* module static variables */
static ncx_module_t *sil_error_mod;


/********************************************************************
* FUNCTION process_callback_error
* 
* Process the edit request on the sil-trigger object.
* Use the sil-phase sibling object for this one to determine
* if NO_ERR or ERR_NCX_OPERATION_FAILED should be returned
*
* INPUTS:
*   cbtyp == callback phase
*   newval == value node from new tree to use (may be NULL)
*   curval == value node from current tree to use (may be NULL)
*
* RETURNS:
*   status
********************************************************************/
static status_t
    process_callback_error (agt_cbtyp_t cbtyp,
                            val_value_t *newval,
                            val_value_t *curval)
{
    /* get the 'best' current parent node */
    val_value_t *parent =
        (curval && curval->parent) ? curval->parent : NULL;
    if (parent == NULL) {
        if (newval && newval->editvars && newval->editvars->curparent) {
            parent = newval->editvars->curparent;
        } else if (newval && newval->parent) {
            parent = newval->parent;
        } else {
            return ERR_NCX_NOT_FOUND;
        }
    }

    status_t res = NO_ERR;

    /* get the sil-trigger sibling object from the parent */
    val_value_t *phase =
        val_find_child(parent, y_sil_error_M_sil_error, 
                       y_sil_error_N_sil_phase);
    if (phase && xml_strcmp(VAL_ENUM_NAME(phase), NCX_EL_NONE) &&
        !xml_strcmp(VAL_ENUM_NAME(phase), agt_cbtype_name(cbtyp))) {

        /* trigger an error in this phase */
        res = ERR_NCX_OPERATION_FAILED;
    }

    return res;

}  /* process_callback_error */


/********************************************************************
* FUNCTION y_sil_error_init_static_vars
* 
* initialize module static variables
* 
********************************************************************/
static void y_sil_error_init_static_vars (void)
{
    sil_error_mod = NULL;

} /* y_sil_error_init_static_vars */


/********************************************************************
* FUNCTION sil_error_sil_trigger_edit
* 
* Edit database object callback
* Path: /sil-trigger
* Add object instrumentation in COMMIT phase.
* 
* INPUTS:
*     see agt/agt_cb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
static status_t sil_error_sil_trigger_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    if (LOGDEBUG) {
        log_debug("\nEnter sil_error_sil_trigger_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    if (editop == OP_EDITOP_NONE) {
        return NO_ERR;
    }

    val_value_t *errorval = (curval) ? curval : newval;
    status_t res = process_callback_error(cbtyp, newval, curval);
    if (res != NO_ERR) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* sil_error_sil_trigger_edit */


/********************************************************************
* FUNCTION sil_error_sil_error_con_sil_trigger_edit
* 
* Edit database object callback
* Path: /sil-error-con/sil-trigger
* Add object instrumentation in COMMIT phase.
* 
* INPUTS:
*     see agt/agt_cb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
static status_t sil_error_sil_error_con_sil_trigger_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    if (LOGDEBUG) {
        log_debug("\nEnter sil_error_sil_error_con_sil_trigger_edit "
                  "callback for %s phase", agt_cbtype_name(cbtyp));
    }

    if (editop == OP_EDITOP_NONE) {
        return NO_ERR;
    }

    val_value_t *errorval = (curval) ? curval : newval;
    status_t res = process_callback_error(cbtyp, newval, curval);
    if (res != NO_ERR) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* sil_error_sil_error_con_sil_trigger_edit */


/********************************************************************
* FUNCTION sil_error_sil_error_list_sil_trigger_edit
* 
* Edit database object callback
* Path: /sil-error-list/sil-trigger
* Add object instrumentation in COMMIT phase.
* 
* INPUTS:
*     see agt/agt_cb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
static status_t sil_error_sil_error_list_sil_trigger_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    if (LOGDEBUG) {
        log_debug("\nEnter sil_error_sil_error_list_sil_trigger_edit "
                  "callback for %s phase", agt_cbtype_name(cbtyp));
    }

    if (editop == OP_EDITOP_NONE) {
        return NO_ERR;
    }

    val_value_t *errorval = (curval) ? curval : newval;
    status_t res = process_callback_error(cbtyp, newval, curval);
    if (res != NO_ERR) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* sil_error_sil_error_list_sil_trigger_edit */


/********************************************************************
* FUNCTION sil_error_sil_error_con2_sil_error_choice_real_sil_trigger_edit
* 
* Edit database object callback
* Path: /sil-error-con2/sil-error-choice/real/sil-trigger
* Add object instrumentation in COMMIT phase.
* 
* INPUTS:
*     see agt/agt_cb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
static status_t
    sil_error_sil_error_con2_sil_error_choice_real_sil_trigger_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    if (LOGDEBUG) {
        log_debug("\nEnter sil_error_sil_error_con2_sil_error_choice"
                  "_real_sil_trigger_edit callback for %s phase",
                  agt_cbtype_name(cbtyp));
    }

    if (editop == OP_EDITOP_NONE) {
        return NO_ERR;
    }

    val_value_t *errorval = (curval) ? curval : newval;
    status_t res = process_callback_error(cbtyp, newval, curval);
    if (res != NO_ERR) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* sil_error_sil_error_con2_sil_error_choice_real_sil_trigger_edit */


/********************************************************************
* FUNCTION y_sil_error_init
* 
* initialize the sil-error server instrumentation library
* 
* INPUTS:
*    modname == requested module name
*    revision == requested version (NULL for any)
* 
* RETURNS:
*     error status
********************************************************************/
status_t y_sil_error_init (
    const xmlChar *modname,
    const xmlChar *revision)
{
    status_t res = NO_ERR;
    agt_profile_t *agt_profile = agt_get_profile();

    y_sil_error_init_static_vars();

    /* change if custom handling done */
    if (xml_strcmp(modname, y_sil_error_M_sil_error)) {
        return ERR_NCX_UNKNOWN_MODULE;
    }

    if (revision && xml_strcmp(revision, y_sil_error_R_sil_error)) {
        return ERR_NCX_WRONG_VERSION;
    }
    res = ncxmod_load_module(
        y_sil_error_M_sil_error,
        y_sil_error_R_sil_error,
        &agt_profile->agt_savedevQ,
        &sil_error_mod);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_callback(
        y_sil_error_M_sil_error,
        (const xmlChar *)"/sil-trigger",
        y_sil_error_R_sil_error,
        sil_error_sil_trigger_edit);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_callback(
        y_sil_error_M_sil_error,
        (const xmlChar *)"/sil-error-con/sil-trigger",
        y_sil_error_R_sil_error,
        sil_error_sil_error_con_sil_trigger_edit);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_callback(
        y_sil_error_M_sil_error,
        (const xmlChar *)"/sil-error-list/sil-trigger",
        y_sil_error_R_sil_error,
        sil_error_sil_error_list_sil_trigger_edit);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_callback(
        y_sil_error_M_sil_error,
        (const xmlChar *)"/sil-error-con2/sil-error-choice/real/sil-trigger",
        y_sil_error_R_sil_error,
        sil_error_sil_error_con2_sil_error_choice_real_sil_trigger_edit);
    if (res != NO_ERR) {
        return res;
    }

    return res;

} /* y_sil_error_init */


/********************************************************************
* FUNCTION y_sil_error_init2
* 
* SIL init phase 2: non-config data structures
* Called after running config is loaded
* 
* RETURNS:
*     error status
********************************************************************/
status_t y_sil_error_init2 (void)
{
    status_t res = NO_ERR;

    return res;
} /* y_sil_error_init2 */


/********************************************************************
* FUNCTION y_sil_error_cleanup
*    cleanup the server instrumentation library
* 
********************************************************************/
void y_sil_error_cleanup (void)
{
    agt_cb_unregister_callbacks(
        y_sil_error_M_sil_error,
        (const xmlChar *)"/sil-trigger");

    agt_cb_unregister_callbacks(
        y_sil_error_M_sil_error,
        (const xmlChar *)"/sil-error-con/sil-trigger");

    agt_cb_unregister_callbacks(
        y_sil_error_M_sil_error,
        (const xmlChar *)"/sil-error-list/sil-trigger");

    agt_cb_unregister_callbacks(
        y_sil_error_M_sil_error,
        (const xmlChar *)"/sil-error-con2/sil-error-choice/real/sil-trigger");

} /* y_sil_error_cleanup */

/* END sil_error.c */
